name: KernelSU (rsuntk) Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        type:
          [
            aosp-12-e,
          ]

    steps:
      - uses: actions/checkout@v3

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Manila"
          timezoneMacos: "Asia/Manila"
          timezoneWindows: "Philippine Standard Time"

      - name: Export build branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        id: branch_name

      - name: Update Debian/Ubuntu Repositories
        run: sudo apt-get update

      - name: Install Debian/Ubuntu dependencies
        run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq -y

      - name: Parse build arguments
        run: |
          echo "VARIANT=$(echo ${{ matrix.type }} | cut -d '-' -f1)" >> $GITHUB_ENV
          echo "ANDROID=$(echo ${{ matrix.type }} | cut -d '-' -f2)" >> $GITHUB_ENV
          echo "SELINUX=$(echo ${{ matrix.type }} | cut -d '-' -f3)" >> $GITHUB_ENV

      - name: Build Mint kernel (KernelSU)
        run: |
          set -eo pipefail
          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          rm build.sh
          wget -O build.sh https://raw.githubusercontent.com/fityanferry/android_kernel_samsung_exynos9610_mint/refs/heads/manual-patch-susfs/build-ksu-rsuntk.sh
          chmod +x build.sh
          ./build.sh --automated --device a50 --variant $VARIANT --android $ANDROID -$SELINUX --kernelsu

      - name: Upload kernel image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type }} Kernel Image (KernelSU)
          path: "out/boot.img"
          if-no-files-found: error

      - name: Prepare release package
        run: |
          mkdir -p ./release
          mv -f `find ./out -iname "MintBeta-*.zip"` ./release/

      - name: Prepare build config artifact
        run: cp .config ./release/kernel_config_a50_$VARIANT-$ANDROID-$SELINUX.txt

      - name: Upload release package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type }} Release
          path: "release"
          if-no-files-found: error

      - name: Upload build config artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type }} Kernel Configs
          path: release/kernel_config_a50_${{ env.VARIANT }}-${{ env.ANDROID }}-${{ env.SELINUX }}.txt
          if-no-files-found: error
